name: memote run

on: pull_request

jobs:
  memote-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Memote on PR
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/metabolicatlas/memote-docker:0.13
          options: -v ${{ github.workspace }}:/opt
          shell: bash
          run: |
            cd /opt
            touch .env
            python -c 'import code.io as io; model = io.read_yeast_model(make_bigg_compliant=True); io.write_yeast_model(model)'
            memote run --ignore-git --solver-timeout 30
